### ISSUE TITLE
Write up Katie's notes on uploading to the Wiki!

### ISSUE THREAD

**Issue by KOXLEY2** [Sheffield-iGE/.github#75]

**Comment by TheLostLambda** [comment]
Are these ready?

**Comment by Gheist404** [comment]
@TheLostLambda I had written this a while ago and needed to check if the end bit sounded right because the rest seems okay but the section about git seems a bit lack luster should more be added or is it better if there is more of a visual aspect because I feel there's less visual aid in this write up of Katie's whereas Katie's was superior on images. Opinions??? 

Here's the link: https://docs.google.com/document/d/1oFbrilAzmNz-H0KjyfJNDCvU0WBWKSqcdJ-a2eBzTiA/edit?usp=drive_link
Also can be found in the Wiki folder and is called How to Wiki

**Comment by TheLostLambda** [comment]
It looks pretty good overall! If you want, you could toss in some of this for the git sections, but with what we're doing, I'm not sure if it's quite worth it? https://git-school.github.io/visualizing-git/#free-remote

I'll leave a couple of comments, but the only other thing I can think linking to some resources for installing all of the tools on a couple of different platforms?

Perhaps it would be overall helpful if there was some narrative being followed? Like you want to add an image to the wiki, here are the edits you need to make to these files, here is where you host the image, etc?

**Adding something about asset / image uploading + showing a real change being made to the wiki with some screenshots could help!**
